language: python
python:
 - "3.6"

sudo: required

services:
 - docker

before_install:
  - docker-compose build
  - docker-compose up -d
  - docker ps -a
  - docker run --env POSTGRES_HOST="hackerspace_db_1" --env REDIS_HOST="hackerspace_redis_1" hackerspace_web /bin/sh -c "python src/manage.py test src && flake8 src"
 
script: 
 - docker run --env POSTGRES_HOST="hackerspace_db_1" --env REDIS_HOST="hackerspace_redis_1" hackerspace_web /bin/sh -c "python src/manage.py test src && flake8 src"
