language: python
python:
 - "3.6"

services:
 - docker

before_install: 
  - pip install docker-compose --no-cache-dir
  - docker-compose build
  - docker-compose up -d

script: 
 - docker run hackerspace_web_1 sh -c "python src/manage.py test src && flake8 src"
