language: python
python:
 - "3.6"

sudo: required

services:
 - docker

before_install: 
  - pip install docker-compose --no-cache-dir
  - docker-compose build
  - docker-compose up -d

install:
  - sudo docker images
 
script: 
 - docker run hackerspace_web sh -c "python src/manage.py test src && flake8 src"
